// AUTO-GENERATED from ICU data. Do not hand-edit.
// ISO 3166-1 alpha-2 codes with Estonian and English names, sorted by Estonian name.

export interface Country {
  code: string;
  et: string;
  en: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', et: "Afganistan", en: "Afghanistan" },
  { code: 'AL', et: "Albaania", en: "Albania" },
  { code: 'DZ', et: "Alžeeria", en: "Algeria" },
  { code: 'US', et: "Ameerika Ühendriigid", en: "United States" },
  { code: 'AD', et: "Andorra", en: "Andorra" },
  { code: 'AO', et: "Angola", en: "Angola" },
  { code: 'AI', et: "Anguilla", en: "Anguilla" },
  { code: 'AG', et: "Antigua ja Barbuda", en: "Antigua & Barbuda" },
  { code: 'AE', et: "Araabia Ühendemiraadid", en: "United Arab Emirates" },
  { code: 'AR', et: "Argentina", en: "Argentina" },
  { code: 'AM', et: "Armeenia", en: "Armenia" },
  { code: 'AW', et: "Aruba", en: "Aruba" },
  { code: 'AZ', et: "Aserbaidžaan", en: "Azerbaijan" },
  { code: 'AU', et: "Austraalia", en: "Australia" },
  { code: 'AT', et: "Austria", en: "Austria" },
  { code: 'BS', et: "Bahama", en: "Bahamas" },
  { code: 'BH', et: "Bahrein", en: "Bahrain" },
  { code: 'BD', et: "Bangladesh", en: "Bangladesh" },
  { code: 'BB', et: "Barbados", en: "Barbados" },
  { code: 'PW', et: "Belau", en: "Palau" },
  { code: 'BE', et: "Belgia", en: "Belgium" },
  { code: 'BZ', et: "Belize", en: "Belize" },
  { code: 'BJ', et: "Benin", en: "Benin" },
  { code: 'BT', et: "Bhutan", en: "Bhutan" },
  { code: 'BO', et: "Boliivia", en: "Bolivia" },
  { code: 'BA', et: "Bosnia ja Hertsegoviina", en: "Bosnia & Herzegovina" },
  { code: 'BW', et: "Botswana", en: "Botswana" },
  { code: 'BR', et: "Brasiilia", en: "Brazil" },
  { code: 'BN', et: "Brunei", en: "Brunei" },
  { code: 'BG', et: "Bulgaaria", en: "Bulgaria" },
  { code: 'BF', et: "Burkina Faso", en: "Burkina Faso" },
  { code: 'BI', et: "Burundi", en: "Burundi" },
  { code: 'CO', et: "Colombia", en: "Colombia" },
  { code: 'CR', et: "Costa Rica", en: "Costa Rica" },
  { code: 'DJ', et: "Djibouti", en: "Djibouti" },
  { code: 'DM', et: "Dominica", en: "Dominica" },
  { code: 'DO', et: "Dominikaani Vabariik", en: "Dominican Republic" },
  { code: 'EC', et: "Ecuador", en: "Ecuador" },
  { code: 'EE', et: "Eesti", en: "Estonia" },
  { code: 'EG', et: "Egiptus", en: "Egypt" },
  { code: 'GQ', et: "Ekvatoriaal-Guinea", en: "Equatorial Guinea" },
  { code: 'SV', et: "El Salvador", en: "El Salvador" },
  { code: 'CI', et: "Elevandiluurannik", en: "Côte d’Ivoire" },
  { code: 'ER', et: "Eritrea", en: "Eritrea" },
  { code: 'ET', et: "Etioopia", en: "Ethiopia" },
  { code: 'FJ', et: "Fidži", en: "Fiji" },
  { code: 'PH', et: "Filipiinid", en: "Philippines" },
  { code: 'GA', et: "Gabon", en: "Gabon" },
  { code: 'GM', et: "Gambia", en: "Gambia" },
  { code: 'GH', et: "Ghana", en: "Ghana" },
  { code: 'GD', et: "Grenada", en: "Grenada" },
  { code: 'GE', et: "Gruusia", en: "Georgia" },
  { code: 'GT', et: "Guatemala", en: "Guatemala" },
  { code: 'GN', et: "Guinea", en: "Guinea" },
  { code: 'GW', et: "Guinea-Bissau", en: "Guinea-Bissau" },
  { code: 'GY', et: "Guyana", en: "Guyana" },
  { code: 'HT', et: "Haiti", en: "Haiti" },
  { code: 'CN', et: "Hiina", en: "China" },
  { code: 'ES', et: "Hispaania", en: "Spain" },
  { code: 'NL', et: "Holland", en: "Netherlands" },
  { code: 'HN', et: "Honduras", en: "Honduras" },
  { code: 'HR', et: "Horvaatia", en: "Croatia" },
  { code: 'TL', et: "Ida-Timor", en: "Timor-Leste" },
  { code: 'IE', et: "Iirimaa", en: "Ireland" },
  { code: 'IL', et: "Iisrael", en: "Israel" },
  { code: 'IN', et: "India", en: "India" },
  { code: 'ID', et: "Indoneesia", en: "Indonesia" },
  { code: 'IQ', et: "Iraak", en: "Iraq" },
  { code: 'IR', et: "Iraan", en: "Iran" },
  { code: 'IS', et: "Island", en: "Iceland" },
  { code: 'IT', et: "Itaalia", en: "Italy" },
  { code: 'JP', et: "Jaapan", en: "Japan" },
  { code: 'JM', et: "Jamaica", en: "Jamaica" },
  { code: 'YE', et: "Jeemen", en: "Yemen" },
  { code: 'JO', et: "Jordaania", en: "Jordan" },
  { code: 'KH', et: "Kambodža", en: "Cambodia" },
  { code: 'CM', et: "Kamerun", en: "Cameroon" },
  { code: 'CA', et: "Kanada", en: "Canada" },
  { code: 'KZ', et: "Kasahstan", en: "Kazakhstan" },
  { code: 'QA', et: "Katar", en: "Qatar" },
  { code: 'KE', et: "Keenia", en: "Kenya" },
  { code: 'CF', et: "Kesk-Aafrika Vabariik", en: "Central African Republic" },
  { code: 'KI', et: "Kiribati", en: "Kiribati" },
  { code: 'KM', et: "Komoorid", en: "Comoros" },
  { code: 'CD', et: "Kongo DV", en: "Congo - Kinshasa" },
  { code: 'CG', et: "Kongo Vabariik", en: "Congo - Brazzaville" },
  { code: 'XK', et: "Kosovo", en: "Kosovo" },
  { code: 'GR', et: "Kreeka", en: "Greece" },
  { code: 'CU', et: "Kuuba", en: "Cuba" },
  { code: 'KW', et: "Kuveit", en: "Kuwait" },
  { code: 'KG', et: "Kõrgõzstan", en: "Kyrgyzstan" },
  { code: 'CY', et: "Küpros", en: "Cyprus" },
  { code: 'LA', et: "Laos", en: "Laos" },
  { code: 'LT', et: "Leedu", en: "Lithuania" },
  { code: 'LS', et: "Lesotho", en: "Lesotho" },
  { code: 'LR', et: "Libeeria", en: "Liberia" },
  { code: 'LI', et: "Liechtenstein", en: "Liechtenstein" },
  { code: 'LB', et: "Liibanon", en: "Lebanon" },
  { code: 'LY', et: "Liibüa", en: "Libya" },
  { code: 'LU', et: "Luksemburg", en: "Luxembourg" },
  { code: 'ZA', et: "Lõuna-Aafrika Vabariik", en: "South Africa" },
  { code: 'KR', et: "Lõuna-Korea", en: "South Korea" },
  { code: 'SS', et: "Lõuna-Sudaan", en: "South Sudan" },
  { code: 'LV', et: "Läti", en: "Latvia" },
  { code: 'MG', et: "Madagaskar", en: "Madagascar" },
  { code: 'MY', et: "Malaisia", en: "Malaysia" },
  { code: 'MW', et: "Malawi", en: "Malawi" },
  { code: 'MV', et: "Maldiivid", en: "Maldives" },
  { code: 'ML', et: "Mali", en: "Mali" },
  { code: 'MT', et: "Malta", en: "Malta" },
  { code: 'MA', et: "Maroko", en: "Morocco" },
  { code: 'MH', et: "Marshalli Saared", en: "Marshall Islands" },
  { code: 'MR', et: "Mauritaania", en: "Mauritania" },
  { code: 'MU', et: "Mauritius", en: "Mauritius" },
  { code: 'MX', et: "Mehhiko", en: "Mexico" },
  { code: 'FM', et: "Mikroneesia", en: "Micronesia" },
  { code: 'MD', et: "Moldova", en: "Moldova" },
  { code: 'MC', et: "Monaco", en: "Monaco" },
  { code: 'MN', et: "Mongoolia", en: "Mongolia" },
  { code: 'ME', et: "Montenegro", en: "Montenegro" },
  { code: 'MZ', et: "Mosambiik", en: "Mozambique" },
  { code: 'MM', et: "Myanmar (Birma)", en: "Myanmar (Burma)" },
  { code: 'NA', et: "Namiibia", en: "Namibia" },
  { code: 'NR', et: "Nauru", en: "Nauru" },
  { code: 'NP', et: "Nepal", en: "Nepal" },
  { code: 'NI', et: "Nicaragua", en: "Nicaragua" },
  { code: 'NG', et: "Nigeeria", en: "Nigeria" },
  { code: 'NE', et: "Niger", en: "Niger" },
  { code: 'NO', et: "Norra", en: "Norway" },
  { code: 'OM', et: "Omaan", en: "Oman" },
  { code: 'PG', et: "Paapua Uus-Guinea", en: "Papua New Guinea" },
  { code: 'PK', et: "Pakistan", en: "Pakistan" },
  { code: 'PA', et: "Panama", en: "Panama" },
  { code: 'PY', et: "Paraguay", en: "Paraguay" },
  { code: 'PE', et: "Peruu", en: "Peru" },
  { code: 'PL', et: "Poola", en: "Poland" },
  { code: 'PT', et: "Portugal", en: "Portugal" },
  { code: 'FR', et: "Prantsusmaa", en: "France" },
  { code: 'KP', et: "Põhja-Korea", en: "North Korea" },
  { code: 'MK', et: "Põhja-Makedoonia", en: "North Macedonia" },
  { code: 'CV', et: "Roheneemesaared", en: "Cape Verde" },
  { code: 'SE', et: "Rootsi", en: "Sweden" },
  { code: 'RO', et: "Rumeenia", en: "Romania" },
  { code: 'RW', et: "Rwanda", en: "Rwanda" },
  { code: 'SB', et: "Saalomoni Saared", en: "Solomon Islands" },
  { code: 'KN', et: "Saint Kitts ja Nevis", en: "St. Kitts & Nevis" },
  { code: 'LC', et: "Saint Lucia", en: "St. Lucia" },
  { code: 'VC', et: "Saint Vincent ja Grenadiinid", en: "St. Vincent & Grenadines" },
  { code: 'DE', et: "Saksamaa", en: "Germany" },
  { code: 'ZM', et: "Sambia", en: "Zambia" },
  { code: 'WS', et: "Samoa", en: "Samoa" },
  { code: 'SM', et: "San Marino", en: "San Marino" },
  { code: 'ST', et: "São Tomé ja Príncipe", en: "São Tomé & Príncipe" },
  { code: 'SA', et: "Saudi Araabia", en: "Saudi Arabia" },
  { code: 'SC', et: "Seišellid", en: "Seychelles" },
  { code: 'SN', et: "Senegal", en: "Senegal" },
  { code: 'RS', et: "Serbia", en: "Serbia" },
  { code: 'SL', et: "Sierra Leone", en: "Sierra Leone" },
  { code: 'SG', et: "Singapur", en: "Singapore" },
  { code: 'SK', et: "Slovakkia", en: "Slovakia" },
  { code: 'SI', et: "Sloveenia", en: "Slovenia" },
  { code: 'SO', et: "Somaalia", en: "Somalia" },
  { code: 'FI', et: "Soome", en: "Finland" },
  { code: 'LK', et: "Sri Lanka", en: "Sri Lanka" },
  { code: 'SD', et: "Sudaan", en: "Sudan" },
  { code: 'SR', et: "Suriname", en: "Suriname" },
  { code: 'SZ', et: "Svaasimaa", en: "Eswatini" },
  { code: 'SY', et: "Süüria", en: "Syria" },
  { code: 'CH', et: "Šveits", en: "Switzerland" },
  { code: 'ZW', et: "Zimbabwe", en: "Zimbabwe" },
  { code: 'DK', et: "Taani", en: "Denmark" },
  { code: 'TJ', et: "Tadžikistan", en: "Tajikistan" },
  { code: 'TH', et: "Tai", en: "Thailand" },
  { code: 'TW', et: "Taiwan", en: "Taiwan" },
  { code: 'TZ', et: "Tansaania", en: "Tanzania" },
  { code: 'TG', et: "Togo", en: "Togo" },
  { code: 'TO', et: "Tonga", en: "Tonga" },
  { code: 'TT', et: "Trinidad ja Tobago", en: "Trinidad & Tobago" },
  { code: 'TD', et: "Tšaad", en: "Chad" },
  { code: 'CZ', et: "Tšehhi", en: "Czechia" },
  { code: 'CL', et: "Tšiili", en: "Chile" },
  { code: 'TN', et: "Tuneesia", en: "Tunisia" },
  { code: 'TV', et: "Tuvalu", en: "Tuvalu" },
  { code: 'TR', et: "Türgi", en: "Türkiye" },
  { code: 'TM', et: "Türkmenistan", en: "Turkmenistan" },
  { code: 'UG', et: "Uganda", en: "Uganda" },
  { code: 'UA', et: "Ukraina", en: "Ukraine" },
  { code: 'HU', et: "Ungari", en: "Hungary" },
  { code: 'UY', et: "Uruguay", en: "Uruguay" },
  { code: 'UZ', et: "Usbekistan", en: "Uzbekistan" },
  { code: 'NZ', et: "Uus-Meremaa", en: "New Zealand" },
  { code: 'BY', et: "Valgevene", en: "Belarus" },
  { code: 'VU', et: "Vanuatu", en: "Vanuatu" },
  { code: 'VA', et: "Vatikan", en: "Vatican City" },
  { code: 'RU', et: "Venemaa", en: "Russia" },
  { code: 'VE', et: "Venezuela", en: "Venezuela" },
  { code: 'VN', et: "Vietnam", en: "Vietnam" },
  { code: 'GB', et: "Ühendkuningriik", en: "United Kingdom" },
];

/**
 * EEA (EU 27 + Iceland, Liechtenstein, Norway) plus Switzerland.
 *
 * Turismiseadus § 24(3): citizens of these states do not need to provide travel
 * document details. Everyone else does, unless they hold Estonian residence.
 * Mirrored by the `turs_24_3_document_required` CHECK constraint in the database —
 * change both together.
 */
export const EEA_AND_CH = new Set<string>([
  'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU',
  'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES',
  'SE',
  'IS', 'LI', 'NO',
  'CH',
]);

export function countryName(code: string, locale: 'et' | 'en'): string {
  return COUNTRIES.find((c) => c.code === code)?.[locale] ?? code;
}

/**
 * Turismiseadus § 24(3) — must this guest supply travel document details?
 *
 * § 24(2) exempts two groups: EEA/Swiss citizens, and third-country nationals
 * residing in Estonia on a residence permit or right of residence. The second
 * is inferred from country of residence rather than asked about separately.
 *
 * Mirrors public.turs_requires_document() in the SQL migration — change both.
 */
export function needsTravelDocument(citizenship: string, countryOfResidence: string): boolean {
  if (citizenship === '') return false;
  if (EEA_AND_CH.has(citizenship)) return false;
  if (countryOfResidence === 'EE') return false;
  return true;
}
